Repository Deep-dive-final-project/DeepDive-API, pull requests merged in 2024-09, with the labels that each got.

#1 ✨ Feat 강의 노트 구현에 필요한 클래스와 패키지 구조 정의
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/dto/request/request.txt
  src/main/java/org/deepdive/apiserver/note/application/dto/response/response.txt
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/domain/Note.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/note/repository/jpa/JpaNoteRepository.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
Labels: :gear: Setting

#3 ✨ Feat 로그인 구현
  src/main/java/org/deepdive/apiserver/security/application/AuthService.java
  src/main/java/org/deepdive/apiserver/security/application/CustomUserDetails.java
  src/main/java/org/deepdive/apiserver/security/application/CustomUserDetailsService.java
  src/main/java/org/deepdive/apiserver/security/application/dto/request/SignupDto.java
  src/main/java/org/deepdive/apiserver/security/application/handler/CustomLoginFailureHandler.java
  src/main/java/org/deepdive/apiserver/security/application/handler/CustomLoginSuccessHandler.java
  src/main/java/org/deepdive/apiserver/security/application/interfaces/MemberRepository.java
  src/main/java/org/deepdive/apiserver/security/application/resolver/Login.java
  src/main/java/org/deepdive/apiserver/security/application/resolver/SessionArgumentResolver.java
  src/main/java/org/deepdive/apiserver/security/config/SecurityConfig.java
  src/main/java/org/deepdive/apiserver/security/domain/Member.java
  src/main/java/org/deepdive/apiserver/security/repository/MemberRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/security/repository/entity/MemberEntity.java
  src/main/java/org/deepdive/apiserver/security/service/CustomUserDetailsService.java
  src/main/java/org/deepdive/apiserver/security/ui/AuthController.java
Labels: :sparkles: Feat

#10 :hammer: [Refactor] 로그인 구현까지 merge하기 위한 리팩토링
  src/main/java/org/deepdive/apiserver/common/config/WebMvcConfig.java
  src/main/java/org/deepdive/apiserver/lecture/ui/LectureController.java
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/domain/Note.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
  src/main/java/org/deepdive/apiserver/security/repository/MemberRepository.java
  src/main/java/org/deepdive/apiserver/security/repository/jpa/JpaMemberRepository.java
Labels: :hammer: Refactor

#4 ✨ Feat 사용자(내) 강의 목록 이름 조회
  src/main/java/org/deepdive/apiserver/common/config/WebMvcConfig.java
  src/main/java/org/deepdive/apiserver/lecture/application/LectureService.java
  src/main/java/org/deepdive/apiserver/lecture/application/ParseService.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetLectureListResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetLectureResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/interfaces/LectureRepository.java
  src/main/java/org/deepdive/apiserver/lecture/domain/Lecture.java
  src/main/java/org/deepdive/apiserver/lecture/domain/Task.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/Lecture.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/LectureInfo.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/LecturePrice.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/Rating.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/Url.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/stringlist/Goal.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/stringlist/Goals.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/stringlist/StringList.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/stringlist/Target.java
  src/main/java/org/deepdive/apiserver/lecture/domain/lecture/stringlist/Targets.java
  src/main/java/org/deepdive/apiserver/lecture/repository/LectureRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/LectureEntity.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/LectureInfoEntity.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/MyLectureEntity.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/StringToListConverter.java
  src/main/java/org/deepdive/apiserver/lecture/repository/jpa/JpaLectureCommandRepository.java
  src/main/java/org/deepdive/apiserver/lecture/repository/jpa/JpaLectureQueryRepository.java
  src/main/java/org/deepdive/apiserver/lecture/repository/jpa/JpaMyLectureQueryRepository.java
  src/main/java/org/deepdive/apiserver/lecture/ui/LectureController.java
  src/main/java/org/deepdive/apiserver/security/repository/MemberRepository.java
  src/main/java/org/deepdive/apiserver/security/repository/entity/MemberEntity.java
  src/main/java/org/deepdive/apiserver/security/repository/jpa/JpaMemberRepository.java
Labels: :sparkles: Feat

#11 ✨ Feat 강의 노트 조회 구현
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/dto/response/GetNoteResponseDto.java
  src/main/java/org/deepdive/apiserver/note/application/dto/response/response.txt
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
Labels: :sparkles: Feat

#12 🔨 fix lecture 조회 수정 & member 조회 추가
  src/main/java/org/deepdive/apiserver/lecture/application/LectureService.java
  src/main/java/org/deepdive/apiserver/lecture/application/ParseService.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/request/request.txt
  src/main/java/org/deepdive/apiserver/security/application/MemberService.java
  src/main/java/org/deepdive/apiserver/security/application/interfaces/MemberRepository.java
  src/main/java/org/deepdive/apiserver/security/repository/MemberRepositoryImpl.java
Labels: :lady_beetle: fix

#13 ✨ Feat 강의 노트 생성 구현
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/dto/request/CreateNoteRequestDto.java
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/domain/Note.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
Labels: :sparkles: Feat

#5 ✨ Feat 강의 섹션 조회
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/lecture/application/SectionService.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetSectionListResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetSectionResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/interfaces/SectionRepository.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/Section.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/subsection/SubSection.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/subsection/SubSections.java
  src/main/java/org/deepdive/apiserver/lecture/repository/SectionRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/SectionEntity.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/StringToListConverter.java
  src/main/java/org/deepdive/apiserver/lecture/repository/jpa/JpaSectionQueryRepository.java
  src/main/java/org/deepdive/apiserver/lecture/ui/SectionController.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#14 🔨 Fix lecture findAllByLectureId @param 오류 해결
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/lecture/application/SectionService.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetSectionListResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/dto/response/GetSectionResponseDto.java
  src/main/java/org/deepdive/apiserver/lecture/application/interfaces/SectionRepository.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/Section.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/subsection/SubSection.java
  src/main/java/org/deepdive/apiserver/lecture/domain/section/subsection/SubSections.java
  src/main/java/org/deepdive/apiserver/lecture/repository/SectionRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/SectionEntity.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/StringToListConverter.java
  src/main/java/org/deepdive/apiserver/lecture/repository/jpa/JpaSectionQueryRepository.java
  src/main/java/org/deepdive/apiserver/lecture/ui/SectionController.java
Labels: :hammer: Refactor, :lady_beetle: fix

#9 ✨ Feat 퀘스트 조회
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/quest/application/QuestService.java
  src/main/java/org/deepdive/apiserver/quest/application/dto/GetQuestDetailResponseDto.java
  src/main/java/org/deepdive/apiserver/quest/application/interfaces/QuestRepository.java
  src/main/java/org/deepdive/apiserver/quest/repository/QuestRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/quest/ui/QuestController.java
Labels: :sparkles: Feat

#15 ✨ Feat 강의 노트 편집 구현
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/dto/request/UpdateNoteRequestDto.java
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/domain/Note.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/note/repository/jpa/JpaNoteRepository.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
  src/main/java/org/deepdive/apiserver/security/domain/Member.java
Labels: :sparkles: Feat, :hammer: Refactor

#16 :sparkles: [Feat] 강의 노트 삭제 구현
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/interfaces/NoteRepository.java
  src/main/java/org/deepdive/apiserver/note/repository/NoteRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
Labels: :sparkles: Feat

#17 [fix] quest member 추가, oop 지향 코드
  src/main/java/org/deepdive/apiserver/lecture/application/LectureService.java
  src/main/java/org/deepdive/apiserver/lecture/application/SectionService.java
  src/main/java/org/deepdive/apiserver/lecture/application/interfaces/LectureRepository.java
  src/main/java/org/deepdive/apiserver/lecture/application/interfaces/SectionRepository.java
  src/main/java/org/deepdive/apiserver/lecture/repository/LectureRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/lecture/repository/SectionRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/lecture/repository/entity/SectionEntity.java
  src/main/java/org/deepdive/apiserver/lecture/ui/LectureController.java
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/quest/application/QuestService.java
  src/main/java/org/deepdive/apiserver/quest/application/interfaces/QuestRepository.java
  src/main/java/org/deepdive/apiserver/quest/domain/Quest.java
  src/main/java/org/deepdive/apiserver/quest/repository/QuestRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/quest/repository/entity/QuestEntity.java
  src/main/java/org/deepdive/apiserver/quest/repository/jpa/JpaQuestQueryRepository.java
  src/main/java/org/deepdive/apiserver/quest/ui/QuestController.java
Labels: bug, :hammer: Refactor

#18 ✨Feat : 메인 페이지 진행중인 학습 계획 목록 조회
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlanResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlansResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/PlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/domain/Plan.java
  src/main/java/org/deepdive/apiserver/plan/repository/PlanRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/PlanEntity.java
  src/main/java/org/deepdive/apiserver/plan/repository/jpa/JpaPlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/ui/PlanController.java
  src/main/java/org/deepdive/apiserver/security/repository/MemberRepository.java
Labels: :sparkles: Feat

#19 ✨Feat: BE-12 학습 계획 목록 조회 구현
  \
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlanForMainPageResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlanForPlanPageResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlansForMainPageResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlansForPlanPageResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlansResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/ui/PlanController.java
Labels: :sparkles: Feat

#20 ✨Feat : BE-13 단일 학습 계획 조회 구현
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/PlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/repository/PlanRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/jpa/JpaPlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/ui/PlanController.java
Labels: :sparkles: Feat

#21 ✨Feat : BE-15 학습 계획 삭제 구현
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetPlanDetailResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/PlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/domain/Plan.java
  src/main/java/org/deepdive/apiserver/plan/repository/PlanRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/PlanEntity.java
  src/main/java/org/deepdive/apiserver/plan/repository/jpa/JpaPlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/ui/PlanController.java
Labels: :sparkles: Feat

#22 :sparkles: [Feat] Dockerfile 생성 및 gradle 관련 설정
  Dockerfile
  build.gradle
  src/main/resources/application.yml
Labels: :earth_asia: Deployment

#23 ✨ [Feat] Task 로직에 필요한 클래스 구현
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/TaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/domain/Task.java
  src/main/java/org/deepdive/apiserver/plan/repository/TaskRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/TaskEntity.java
  src/main/java/org/deepdive/apiserver/plan/repository/jpa/JpaTaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/ui/TaskController.java
  src/main/resources/application.yml
Labels: :sparkles: Feat

#24 :hammer: [Refactor] note 로직에 task 추가
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/domain/Note.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/TaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/repository/TaskRepositoryImpl.java
Labels: :hammer: Refactor

#25 :sparkles: [Feat] Task 목록 조회 구현
  src/main/java/org/deepdive/apiserver/common/exception/ErrorCode.java
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/response/GetTaskListResponseDto.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/PlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/TaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/repository/PlanRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/TaskRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/jpa/JpaTaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/ui/TaskController.java
Labels: :sparkles: Feat

#26 ✨Feat : BE-14 학습 계획 생성 구현
  src/main/java/org/deepdive/apiserver/plan/application/PlanService.java
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/request/CreatePlanRequestDto.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/PlanRepository.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/TaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/domain/Plan.java
  src/main/java/org/deepdive/apiserver/plan/domain/Task.java
  src/main/java/org/deepdive/apiserver/plan/repository/PlanRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/TaskRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/PlanEntity.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/TaskEntity.java
  src/main/java/org/deepdive/apiserver/plan/ui/PlanController.java
Labels: :sparkles: Feat

#28 🔨Refactor : TaskService 와 PlanService의 순환참조 문제 해결
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
Labels: :hammer: Refactor

#29 ✨Feat : BE-16 테스크 상태 변경
  src/main/java/org/deepdive/apiserver/plan/application/TaskService.java
  src/main/java/org/deepdive/apiserver/plan/application/dto/request/UpdateTaskRequestDto.java
  src/main/java/org/deepdive/apiserver/plan/application/interfaces/TaskRepository.java
  src/main/java/org/deepdive/apiserver/plan/domain/Task.java
  src/main/java/org/deepdive/apiserver/plan/repository/TaskRepositoryImpl.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/TaskEntity.java
  src/main/java/org/deepdive/apiserver/plan/ui/TaskController.java
Labels: :sparkles: Feat

#30 🔨 Refactor : LoacalDate -> TimeStamp & 학습 계획(PlanEntity) 엔티티에 최근 수정일 추가
  src/main/java/org/deepdive/apiserver/common/repository/entity/BaseTimeEntity.java
  src/main/java/org/deepdive/apiserver/note/repository/entity/NoteEntity.java
  src/main/java/org/deepdive/apiserver/plan/repository/entity/PlanEntity.java
  src/main/java/org/deepdive/apiserver/quest/application/dto/GetQuestDetailResponseDto.java
  src/main/java/org/deepdive/apiserver/quest/application/dto/GetQuestResponseDto.java
  src/main/java/org/deepdive/apiserver/quest/domain/Quest.java
  src/main/java/org/deepdive/apiserver/quest/repository/entity/QuestEntity.java
Labels: :hammer: Refactor

#31 🔨Refactor : task 완료시 완료일 등록
  src/main/java/org/deepdive/apiserver/plan/repository/entity/TaskEntity.java
Labels: :hammer: Refactor

#33 :hammers: [Refactor] Note 강의 노트 조회 이중 dto 풀기
  src/main/java/org/deepdive/apiserver/note/application/NoteService.java
  src/main/java/org/deepdive/apiserver/note/application/dto/request/request.txt
  src/main/java/org/deepdive/apiserver/note/application/dto/response/GetLatestNoteListResponseDto.java
  src/main/java/org/deepdive/apiserver/note/ui/NoteController.java
Labels: bug, :lady_beetle: fix
